version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.28
    container_name: langlearning-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: langlearningdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3310:3306" 
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin", "--silent"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s

  langlearning-api:
    build:
      context: .
      dockerfile: LangLearningAPI/Dockerfile
    container_name: langlearning-api
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=langlearningdb;User=admin;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    networks:
      - app-network

  langlearning-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: langlearning-frontend
    ports:
      - "3000:80"
    depends_on:
      - langlearning-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
